export const Label = {
  Name: "Label1",
  Accelerator: "",
  AutoSize: false,
  BackColor: "white",
  BackStyle:"",
  BorderColor: "ghostwhite",
  BorderStyle: "1-fmBorderStyleOpaque",
  Caption: "Label1",
  ControlTipText: "Label1",
  Enabled: true,
  Font: "Tahoma",
  ForeColor: "black",
  Height: "40px",
  HelpContextId: 0,
  Left: "70px",
  MouseIcon: "(None)",
  MousePointer: "default",
  Picture: "(None)",
  PicturePosition: "0 - fmPicturePositionLeftTop",
  SpecialEffect: "none",
  TabIndex: 0,
  TabStop: false,
  Tag: "",
  TextAlign: "left",
  Top: "20px",
  Visible: true,
  Width: "100px",
  WordWrap: "break-word",
 
};
